project:
  type: website
  render: 
    - "index.qmd"
    - "*/*/index.qmd"
    - "preprints.qmd"
    - "by-statsds-topic.qmd"

website:
  title: "SCORE Module Repository"
  page-footer: "Maintained by [Ron Yurko](https://www.stat.cmu.edu/~ryurko/)"
  cookie-consent: true
  google-analytics: "G-D8W3NNYGGP"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - by-statsds-topic.qmd
      - preprints.qmd
      - href: https://data.scorenetwork.org/
        text: Data Repository
      - href: https://scorenetwork.org/index.html
        text: SCORE Network
    right:
      - icon: twitter
        href: https://twitter.com/scorenetworkorg
      - icon: linkedin
        href: https://www.linkedin.com/company/scorenetworkorg/
  sidebar:
    contents: auto
    collapse-level: 1
  repo-url: https://github.com/SCOREnetworkorg/module-repository
  repo-actions: [edit, issue]

format:
  html:
    theme:
      - cosmo
      - score.scss
    toc: true

execute:
  freeze: auto
